const games = [
    {name:"1 On 1 Soccer", url:"./games/1on1-soccer/"},
    {name:"1v1.lol", url:"./games/1v1lol/"},
    {name:"10 Bullets", url:"./games/10-bullets/"},
    {name:"10 Minutes Till Dawn", url:"./games/10-minutes-till-dawn/"},
    {name:"2048", url:"./games/2048/"},
    {name:"A Dance of Fire and Ice", url:"./games/a-dance-of-fire-and-ice/"},
    {name:"Age of War", url:"./games/age-of-war/"},
    {name:"Among Us", url:"./games/among-us/"},
    {name:"Appel", url:"./games/appel/"},
    {name:"Awesome Tanks 2", url:"./games/awesome-tanks-2/"},
    {name:"Bad Ice Cream 3", url:"./games/bad-ice-cream-3/"},
    {name:"Bad Time Simulator", url:"./games/bad-time-simulator/"},
    {name:"Baldi's Basics", url:"./games/baldis-basics/"},
    {name:"Basketball Stars", url:"./games/basketball-stars/"},
    {name:"Big Tower Tiny Square", url:"./games/big-tower-tiny-square/"},
    {name:"Big Tower Tiny Square 2", url:"./games/big-tower-tiny-square-2/"},
    {name:"Bit Planes", url:"./games/bit-planes/"},
    {name:"BitLife", url:"./games/bitlife/"},
    {name:"Block Blast", url:"./games/block-blast/"},
    {name:"Bloons Tower Defense 5", url:"./games/bloons-tower-defense-5/"},
    {name:"Bob The Robber 5", url:"./games/bob-the-robber-5"},
    {name:"Brawl Stars", url:"./games/brawl-stars"},
    {name:"Cookie Clicker", url:"./games/cookie-click/"},
    {name:"Dadish 3", url:"./games/dadish-3/"},
    {name:"Death Run 3D", url:"./games/death-run-3d/"},
    {name:"Doomz.io", url:"./games/doomzio/"},
    {name:"Drift Boss", url:"./games/drift-boss/"},
    {name:"Drive Mad (Fanmade)", url:"./games/drive-mad/"},
    {name:"Duck Life 5", url:"./games/duck-life-5/"},
    {name:"Eaglercraft", url:"./games/eaglercraft/"},
    {name:"Escape Road", url:"./games/escape-road/"},
    {name:"Fireboy and Watergirl 3", url:"./games/fireboy-and-watergirl-3/"},
    {name:"Five Nights at Freddy's 4", url:"./games/five-nights-at-freddys-4/"},
    {name:"Fly the Farthest", url:"./games/fly-the-farthest/"},
    {name:"Fruit Ninja", url:"./games/fruit-ninja/"},
    {name:"Gun Mayhem", url:"./games/gun-mayhem/"},
    {name:"Hei$t", url:"./games/heist/"},
    {name:"Hole.io", url:"./games/holeio/"},
    {name:"Hollow Knight", url:"./games/hollow-knight/"},
    {name:"Justfall.lol", url:"./games/justfalllol/"},
    {name:"Kingdom Rush", url:"./games/kingdom-rush/"},
    {name:"Knights Battle Arena", url:"./games/knights-battle-arena/"},
    {name:"Learn to Fly 3", url:"./games/learn-to-fly-3/"},
    {name:"Melon Playground", url:"./games/melon-playground/"},
    {name:"Monkey Mart", url:"./games/monkey-mart/"},
    {name:"Moto X 3M I", url:"./games/motox3m-1/"},
    {name:"Moto X 3M II", url:"./games/motox3m-2/"},
    {name:"Moto X 3M III", url:"./games/motox3m-3/"},
    {name:"Moto X 3M - Pool Party", url:"./games/motox3m-poolparty/"},
    {name:"Moto X 3M - Spooky Land", url:"./games/motox3m-spookyland/"},
    {name:"Moto X 3M - Winter Land", url:"./games/motox3m-winterland/"},
    {name:"N-Gon", url:"./games/ngon/"},
    {name:"Only Up", url:"./games/only-up/"},
    {name:"OvO Dimensions", url:"./games/ovo-dimensions/"},
    {name:"Paper.io 2", url:"./games/paperio-2/"},
    {name:"Pixel Shooter", url:"./games/pixel-shooter/"},
    {name:"Parking Fury 3", url:"./games/parking-fury-3/"},
    {name:"Plants vs Zombies", url:"./games/plants-vs-zombies/"},
    {name:"PolyTrack", url:"./games/polytrack/"},
    {name:"Rainbow Obby", url:"./games/rainbow-obby/"},
    {name:"Retro Bowl", url:"./games/retrobowl/"},
    {name:"RocketGoal.io", url:"./games/rocketgoalio/"},
    {name:"Rooftop Snipers", url:"./games/rooftop-snipers/"},
    {name:"Run 3", url:"./games/run3/"},
    {name:"Save My Pet", url:"./games/save-my-pet/"},
    {name:"Slope", url:"./games/slope/"},
    {name:"Snake.io", url:"./games/snakeio/"},
    {name:"Snow Rider 3D", url:"./games/snow-rider-3d/"},
    {name:"Snowball.io", url:"./games/snowballio/"},
    {name:"Speed Per Click", url:"./games/speed-per-click/"},
    {name:"Spiral Roll", url:"./games/spiral-roll/"},
    {name:"Steal A Brainrot", url:"./games/steal-a-brainrot/"},
    {name:"Stick War II", url:"./games/stick-war-2/"},
    {name:"Stick Warriors", url:"./games/stick-warriors/"},
    {name:"Stickman Climb", url:"./games/stickman-climb/"},
    {name:"Stickman Hook", url:"./games/stickman-hook/"},
    {name:"Super Mario Bros", url:"./games/super-mario-bros/"},
    {name:"Super Smash Bros", url:"./games/super-smash-bros/"},
    {name:"Swords and Souls", url:"./games/swords-and-souls/"},
    {name:"Temple Run 2", url:"./games/temple-run-2/"},
    {name:"Territorial.io", url:"./games/territorialio/"},
    {name:"Tetris", url:"./games/tetris/"},
    {name:"The Impossible Quiz", url:"./games/the-impossible-quiz/"},
    {name:"The Legend of Zelda: Majora's Mask", url:"./games/the-legend-of-zelda-majoras-mask/"},
    {name:"The Legend of Zelda: Ocarina of Time", url:"./games/the-legend-of-zelda-ocarina-of-time/"},
    {name:"This is the Only Level", url:"./games/this-is-the-only-level/"},
    {name:"Time Shooter 2", url:"./games/time-shooter-2/"},
    {name:"Time Shooter 3 S.W.A.T", url:"./games/time-shooter-3-swat/"},
    {name:"Tiny Fishing", url:"./games/tiny-fishing/"},
    {name:"Tomb of the Mask", url:"./games/tomb-of-the-mask/"},
    {name:"Tunnel Rush 2", url:"./games/tunnel-rush-2/"},
    {name:"Vex 7", url:"./games/vex-7/"},
    {name:"We Become What We Behold", url:"./games/we-become-what-we-behold/"},
    {name:"Wordle+", url:"./games/wordle+/" },
    {name:"World's Hardest Game 3", url:"./games/worlds-hardest-game-3/" }
];
